version: "3"

services:
  app:
    build: .
    restart: always
    container_name: "node"
    ports: 
      - "3334:3333"
    command: npm run dev
    volumes:
      - .:/usr/app
  db:
    image: postgres
    restart: always
    container_name: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "my_database"
    ports:
      - "3001:5432"
volumes:
  pgdata:
